### ISSUE TITLE
How to persist user sessions ?

### ISSUE THREAD

**Issue by wolffparkinson** [MTKruto/MTKruto#245]
How to persist user sessions ?

```ts
import process from "node:process";
import dotenv from "npm:dotenv";
import { Client } from "@mtkruto/mtkruto";
import { StorageDenoKV } from "https://deno.land/x/mtkruto@0.4.0/storage/1_storage_deno_kv.ts";

dotenv.config();

const client = new Client({
  storage: new StorageDenoKV("./auth"),
  apiId: parseInt(`${process.env.API_ID}`),
  apiHash: `${process.env.API_HASH}`,
  persistCache: true,
});

export async function getClient() {
  if (client.connected) return client;

  await client.start();

  return client;
}

export async function run(){
  const client = await getClient();

  const chats = await client.getChats();
  console.log(chats)
}

run()
```

### Problem
The first time program runs, authentication is requested via prompts and the list of chats is displayed.
But the second time program runs, it does not load the saved session/loads incorrectly and shows the following error :
```shell
error: Uncaught (in promise) AssertionError: Unreachable.
  throw new AssertionError(`Unreachable${msgSuffix}`);
        ^
    at unreachable (https://jsr.io/@mtkruto/mtkruto/0.4.0/vendor/jsr.io/@std/assert/1.0.6/unreachable.ts:20:9)
    at peerToChatId (https://jsr.io/@mtkruto/mtkruto/0.4.0/tl/3_utilities.ts:40:5)
    at MessageManager.getMessages (https://jsr.io/@mtkruto/mtkruto/0.4.0/client/3_message_manager.ts:76:21)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async MessageManager.getMessage (https://jsr.io/@mtkruto/mtkruto/0.4.0/client/3_message_manager.ts:118:22)
    at async constructChatListItem (https://jsr.io/@mtkruto/mtkruto/0.4.0/types/5_chat_list_item.ts:49:44)
    at async ChatListManager.#loadChatsFromStorage (https://jsr.io/@mtkruto/mtkruto/0.4.0/client/4_chat_list_manager.ts:190:20)
    at async ChatListManager.getChats (https://jsr.io/@mtkruto/mtkruto/0.4.0/client/4_chat_list_manager.ts:385:7)
    at async Client.getChats (https://jsr.io/@mtkruto/mtkruto/0.4.0/client/5_client.ts:2369:12)
    at async run
```

and sometimes this :
```shell
Uncaught (in promise) AccessError: Cannot access the chat -1001005870615 because there is no access hash for it.
```

**Comment by rojvv** [comment]
The first error could be a bug, depending on what you've passed to the method. We can find out if you show some code.

The second error is a general error that you could face anytime, regardless of having some session data or not.

**Comment by rojvv** [comment]
Closing due to inactivity.
